export let items = [
  {
    id: "1",
    name: "Lightning to lightning/USB",
    type: "Adapter",
    location: "Under counter bottom drawer",
  },
  {
    id: "2",
    name: "Thunderbolt to Ethernet",
    type: "Adapter",
    location: "Under counter bottom drawer",
  },
  {
    id: "3",
    name: "USB C to Ethernet",
    type: "Adapter",
    location: "Under counter bottom drawer",
  },
  {
    id: "4",
    name: "USB A to Ethernet",
    type: "Adapter",
    location: "Under counter bottom drawer",
  },
  {
    id: "5",
    name: "USB C to USB A (Female)",
    type: "Adapter",
    location: "Under counter bottom drawer",
  },
  {
    id: "6",
    name: "USB C mini dock",
    type: "Adapter",
    location: "Under counter bottom drawer",
  },
  {
    id: "7",
    name: "Lightning charger",
    type: "Charger",
    location: "Under counter bottom drawer",
  },
  {
    id: "8",
    name: "Laptop chargers (All)",
    type: "Charger",
    location: "Under counter top drawer",
  },
  {
    id: "9",
    name: "Default power cable",
    type: "Power cable",
    location: "Under counter top drawer",
  },
  {
    id: "10",
    name: "HDMI cable (long)",
    type: "Video cable",
    location: "Closet wood shelf (4)",
  },
  {
    id: "11",
    name: "HDMI cable (short)",
    type: "Video cable",
    location: "Closet wood shelf (4)",
  },
  {
    id: "12",
    name: "HDMI to USB C",
    type: "Video cable",
    location: "Closet wood shelf (4)",
  },
  {
    id: "13",
    name: "Display port",
    type: "Video cable",
    location: "Closet wood shelf (4)",
  },
  {
    id: "14",
    name: "Windows 11 install disks",
    type: "Installation media",
    location: "Closet wood shelf (5)",
  },
  {
    id: "15",
    name: "Philips head screwdriver",
    type: "Tool",
    location: "Closet wood shelf (5)",
  },
  {
    id: "16",
    name: "Flathead screwdriver",
    type: "Tool",
    location: "Closet wood shelf (5)",
  },
  {
    id: "17",
    name: "Needle nose pliers",
    type: "Tool",
    location: "Closet wood shelf (5)",
  },
  {
    id: "18",
    name: "Tweezers",
    type: "Tool",
    location: "Closet wood shelf (5)",
  },
  {
    id: "19",
    name: "Adjustable wrench",
    type: "Tool",
    location: "Closet wood shelf (5)",
  },
  {
    id: "20",
    name: "Torx bits (star head)",
    type: "Tool",
    location: "Closet wood shelf (5)",
  },
  {
    id: "21",
    name: "Flathead bit",
    type: "Tool",
    location: "Closet wood shelf (5)",
  },
  {
    id: "22",
    name: "Philips bit",
    type: "Tool",
    location: "Closet wood shelf (5)",
  },
  {
    id: "23",
    name: "Alan key",
    type: "Tool",
    location: "Closet wood shelf (5)",
  },
  {
    id: "24",
    name: "Screwdriver (removable bit head)",
    type: "Tool",
    location: "Closet wood shelf (5)",
  },
  {
    id: "25",
    name: "Sticky notes",
    type: "Tool",
    location: "Closet wood shelf (5)",
  },
  {
    id: "26",
    name: "3.5 mm audio cable",
    type: "Tool",
    location: "Closet wood shelf (5)",
  },
  {
    id: "27",
    name: "Flashlight",
    type: "Tool",
    location: "Closet wood shelf (5)",
  },
  {
    id: "28",
    name: "RJ45 crimping tool",
    type: "Tool",
    location: "Closet wood shelf (5)",
  },
  {
    id: "29",
    name: "Ethernet cable(long)",
    type: "Cable",
    location: "Closet metal drawer wide (top)",
  },
  {
    id: "30",
    name: "Ethernet cable (short)",
    type: "Cable",
    location: "Closet metal drawer wide (top)",
  },
  {
    id: "31",
    name: "Keyboard",
    type: "Input device",
    location: "Closet metal drawer wide (bottom)",
  },
  {
    id: "32",
    name: "Mouse",
    type: "Input device",
    location: "Closet metal drawer wide (bottom)",
  },
  {
    id: "33",
    name: "Old adapters",
    type: "Adapters",
    location: "Closet metal drawer small (top)",
  },
  {
    id: "34",
    name: "HDD",
    type: "Drive",
    location: "Closet metal drawer small (middle)",
  },
  {
    id: "35",
    name: "SSD",
    type: "Drive",
    location: "Closet metal drawer small (middle)",
  },
  {
    id: "36",
    name: "VGA",
    type: "Cable",
    location: "Closet wood shelf (3)",
  },
  {
    id: "37",
    name: "DVI",
    type: "Cable",
    location: "Closet wood shelf (3)",
  },
  {
    id: "38",
    name: "Earbuds",
    type: "Earbuds",
    location: "Closet wood shelf (3)",
  },

]
