export let service = [
  {
    id: "1",
    name: "filler",
    building: "filler",
    room: "filler",
    ou: "filler",
  },
  {
    id: "2",
    name: "filler",
    building: "filler",
    room: "filler",
    ou: "filler",
  },
  {
    id: "3",
    name: "filler",
    building: "filler",
    room: "filler",
    ou: "filler",
  },
  {
    id: "4",
    name: "filler",
    building: "filler",
    room: "filler",
    ou: "filler",
  },
  {
    id: "5",
    name: "filler",
    building: "filler",
    room: "filler",
    ou: "filler",
  },
  {
    id: "6",
    name: "filler",
    building: "filler",
    room: "filler",
    ou: "filler",
  },
  {
    id: "7",
    name: "filler",
    building: "filler",
    room: "filler",
    ou: "filler",
  },
  {
    id: "8",
    name: "filler",
    building: "filler",
    room: "filler",
    ou: "filler",
  },
  {
    id: "9",
    name: "filler",
    building: "filler",
    room: "filler",
    ou: "filler",
  },
]
